### ISSUE TITLE
Error loading sqlite assembly

### ISSUE THREAD

**Issue by deostroll** [Gobiner/DotNetPad#1]
Hi,

Successfully loaded the solution in vs2010. However, when I try to run the web project I get the following error:

```
Could not load file or assembly 'System.Data.SQLite' or one of its dependencies. An attempt was made to load a program with an incorrect format. 
```

I am aware that there is a setting in vs to run programs in x86, but somehow not getting that right.

**Comment by aaronmrice** [comment]
Hi, sorry I just saw this. I just made some changes to the way the SQLite library gets pulled in. It might have fixed the issue you had.
